build:
  version: "1.0"
  
spring:
  config:
    activate:
      on-profile: "qa"

accounts:
  message: "Welcome to MoneyBank accounts related QA dockerized and webhook implemented APIs "
  contactDetails:
    name: "Smitha M Ray - QA Lead"
    email: "smitha@MoneyBank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371