spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1123.0"

accounts:
  message: "Welcome to MoneyBank accounts related production dockerized and webhook implemented APIs "
  contactDetails:
    name: "Reine M Aishwarya - Product Owner"
    email: "aishwarya@MoneyBank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384