spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to MoneyBank cards related qa webhook2 APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@MoneyBank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267