spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to MoneyBank cards related production dockerized and webhook implementedAPIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@MoneyBank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721