spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to MoneyBank loans related qa dockerized and webhook implemented APIs "
  contactDetails:
    name: "Cyrano M Marita - QA Lead"
    email: "cyrano@MoneyBank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467